### ISSUE TITLE
插件下载完毕 右键点击deployment 没有弹出菜单

### ISSUE THREAD

**Issue by aikin-vip** [nocalhost/nocalhost-intellij-plugin#143]
WebStorm 2021.2.3
内部版本号 #WS-212.5457.55，October 18, 2021 构建
运行时版本: 11.0.12+7-b1504.40 x86_64
VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.
macOS 12.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: org.jetbrains.plugins.go-template (212.5457.62), com.mallowigi (50.1.0), ru.adelf.idea.dotenv (2021.3.0.212), com.chrisrm.idea.MaterialThemeUI (6.9.1), com.intellij.zh (212.325), com.intellij.lang.jsgraphql (3.0.0), dev.nocalhost.nocalhost-intellij-plugin (0.6.4-212), com.intellij.kubernetes (212.5457.4)

**Comment by aikin-vip** [comment]
OK 问题找到。 应该是事件监听的问题。 我用的mac  无鼠标状态下  是以 control+触摸板点击 为鼠标右键，用了下别人的鼠标就出现右键菜单了

**Comment by ovaldi** [comment]
Mac 默认情况下【2个手指头按压触摸板】 就是鼠标右键 @aikin-vip
