### ISSUE TITLE
When will the new version be supported?

### ISSUE THREAD

**Issue by huiwanggo** [nocalhost/nocalhost-intellij-plugin#195]
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/19189837/231051677-8d97bfeb-90c4-4a35-a60e-0ee84a807b74.png">

**Comment by huiwanggo** [comment]
> I've just finished the code change. It going to be released in 2~3 days after some test :)

How is it going?

**Comment by tianyu-sz** [comment]
it's done today :)
