### ISSUE TITLE
temporary fix for remote development high cpu cost

### ISSUE THREAD

**Issue by tianyu-sz** [nocalhost/nocalhost-intellij-plugin#201]
[nocalhost-intellij-plugin-0.0.16-231.zip](https://github.com/nocalhost/nocalhost-intellij-plugin/files/11752726/nocalhost-intellij-plugin-0.0.16-231.zip)

when using jetbrains remote development , high cpu cost was caused by this plugin. Here is a temporary fix for it .

**Comment by tianyu-sz** [comment]
some insight: it looks like the com.intellij.codeWithMe.ClientId implementation miss fired a lot same threads 

the right thread dump running on remote, and it's 158 same threads, while on the left running on local IDEA has only 1 thread to do my job (which is intend)

![wecom-temp-78c9492fe5fc4a6350d93239dc67d198](https://github.com/nocalhost/nocalhost-intellij-plugin/assets/26029007/1a6fc827-de49-466e-acaf-6243fab65a4b)

**Comment by yazhangya** [comment]
hotfix(gateway): fix cpu 100% in jetbrains gateway remote #204

**Comment by tianyu-sz** [comment]
it has been resolved since 0.6.30
