### ISSUE TITLE
Request support for IDEA 2023.2

### ISSUE THREAD

**Issue by HyoKImAbsolut** [nocalhost/nocalhost-intellij-plugin#205]
<img width="844" alt="image" src="https://github.com/nocalhost/nocalhost-intellij-plugin/assets/43777779/4fdeabc1-4020-46bf-812b-73a254c929be">

Thanks for nocalhost maintaince team's work！

**Comment by tianyu-sz** [comment]
looking into it

**Comment by jeffDing2023** [comment]
Has this been fixed?

**Comment by DemonJun** [comment]
looking into it

**Comment by tianyu-sz** [comment]
I upload a single version (Nocalhost 0.6.30-232) zip to jetbrains market manually. It should be available in 2 days after jetbrains reviewing.
