### ISSUE TITLE
The plug-in does not support goland 2024 version?

### ISSUE THREAD

**Issue by snji** [nocalhost/nocalhost-intellij-plugin#219]
<img width="440" alt="image" src="https://github.com/nocalhost/nocalhost-intellij-plugin/assets/73051254/5004849a-916b-497e-b31f-e8ce46b9685c">

**Comment by tianyu-sz** [comment]
not support it yet. I'm working on it

**Comment by tianyu-sz** [comment]
#221 
Jetbrains plugin marketing is reviewing the plugin update.Should be available in 2 days

**Comment by snji** [comment]
> #221 Jetbrains plugin marketing is reviewing the plugin update.Should be available in 2 days

Thank you. If it becomes available for use, please let me know.

**Comment by tianyu-sz** [comment]
it's now available
